name: Connect to an AWS role from a GitHub repository
on:
  push:
    branches: [main]
env:
  AWS_REGION: "us-east-1"

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
        
      - name: Configure and setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::637423591082:role/my-github-user-role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: "637423591082.dkr.ecr.us-east-1.amazonaws.com"
          IMAGE_NAME: "python-app-image"
          TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_NAME:$TAG .
          docker push $ECR_REGISTRY/$IMAGE_NAME:$TAG
